[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tokens = "BwvJoWTxEPDqcogwCzwS2a6jh5Dp87Fz5CtLHLDkPiHT"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
